[package]
name = "ui"
version = "0.1.0"
authors = ["Edward Barnard <eabarnard@gmail.com>"]

[dependencies]
glium = "0.21.0"
imgui = { git = "https://github.com/Gekkio/imgui-rs.git" }
imgui-glium-renderer = { git = "https://github.com/Gekkio/imgui-rs.git" }
