[package]
name = "ui"
version = "0.1.0"
authors = ["Edward Barnard <eabarnard@gmail.com>"]

[dependencies]
glium = "0.18.1"
piston2d-glium_graphics = "0.46.0"
piston2d-graphics = { version = "0.24.0", features = ["glyph_cache_rusttype"] }
