[package]
name = "track"
version = "0.1.0"
authors = ["Edward Barnard <eabarnard@gmail.com>"]

[dependencies]
csv = "1.0.0"
log = "0.4.1"
cubic_spline = { path = "../cubic_spline" }
osqp_wrapper = { path = "../osqp_wrapper" }
prelude = { path = "../prelude" }
sparse = { path = "../sparse" }
