dt = 0.02
track = "../data/tracks/office_desk_track_2500.csv"
N = 100
model = "spengler_gammeter_bicycle"
# Measurement variance
R = [0.000004, 0.000004, 0.0009]
initial_params = [0.07, 3.9, 19.6, 0.0, 14.2, 1.8, 0.0045]
# State evolution variance
Q_state = [0.00005, 0.00005, 0.0001, 0.005]
# Initial parameter variance
Q_initial_params = [0.005, 0.005, 0.000000001, 0.005, 0.004, 0.003, 0.0]
# Q_params = Q_initial_params * Q_params_multiplier
Q_params_multiplier = 0.0000000001
u_min = [0.0, -1.0]
u_max = [0.25, 1.0]
