[package]
name = "visualisation"
version = "0.1.0"
authors = ["Edward Barnard <eabarnard@gmail.com>"]

[dependencies]
control_model = { path = "../control_model" }
prelude = { path = "../prelude" }
track = { path = "../track" }
ui = { path = "../ui" }
