t = 20
dt = 0.01
track = "data/tracks/3yp_track2500.csv"

[controller]
model = "spengler_gammeter_bicycle"
# Measurement variance
R = [0.000004, 0.000004, 0.0009]
initial_params = [0.5, 2.0, 2.0, 1.5, 0.0, 0.0045]
# State evolution variance
Q_state = [0.000005, 0.000005, 0.0005, 0.00001]
# Initial parameter variance
Q_initial_params = [0.05, 2.0, 0.5, 0.4, 0.0, 0.0]
# Q_params = Q_initial_params * Q_params_multiplier
Q_params_multiplier = 0.0000000001

[simulator]
model = "spengler_gammeter_bicycle"
# C1: Steering slip - negative for oversteer, positive for understeer
# C2: Steering angle coupling - radians turned / meter travelled
# Cm1: Duty cycle to acceleration a = Cm1 * throttle
# Cm2 = Cm1 / v_motor_max (i.e. max speed with no air resistance)
# Cr1: Rolling resistance
# Cr2: Reduced air resistance coefficient (0.5 * rho * A * C_d)
params = [0.1, 3.5, 1.0, 0.5, 0.0, 0.0045]
