t = 200
dt = 0.04
track = "../data/tracks/office_desk_track_2500.csv"

[controller]
N = 50
model = "spengler_gammeter_bicycle"
# Measurement variance
R = [0.000004, 0.000004, 0.0009]
initial_params = [0.1, 6.0, 1.0, 0.5, 0.2, 0.0045]
# State evolution variance
Q_state = [0.000005, 0.000005, 0.0005, 0.00001]
# Initial parameter variance
Q_initial_params = [0.05, 2.0, 0.5, 0.4, 0.3, 0.0]
# Q_params = Q_initial_params * Q_params_multiplier
Q_params_multiplier = 0.0000000001

[simulator]
# Run the simulator in real time instead of as fast as possible
real_time = true
model = "spengler_gammeter_bicycle"
# C1: Steering slip - negative for oversteer, positive for understeer
# C2: Steering angle coupling - radians turned / meter travelled
# Cm1: Duty cycle to acceleration a = Cm1 * throttle
# Cm2 = Cm1 / v_motor_max (i.e. max speed with no air resistance)
# Cr1: Rolling resistance
# Cr2: Reduced air resistance coefficient (0.5 * rho * A * C_d)
params = [0.1, 6.0, 1.0, 0.5, 0.2, 0.0045]
