dt = 0.02
track = "../data/tracks/office_desk_track_2500.csv"
N = 50
model = "spengler_gammeter_bicycle"
controller = "mpc_position"
# Measurement variance
R = [0.000004, 0.000004, 0.0009]
initial_params = [0.25, 6.0, 19.6, 11.2, 2.0, 0.0045]
# State evolution variance
Q_state = [0.00005, 0.00005, 0.0001, 0.005]
# Initial parameter variance
Q_initial_params = [0.05, 0.5, 0.5, 0.4, 0.3, 0.0]
# Q_params = Q_initial_params * Q_params_multiplier
Q_params_multiplier = 0.0000000001
u_min = [0.0, -1.0]
u_max = [0.25, 1.0]
