track = "../data/tracks/big_track_2500.csv"
# Measurement variance
R = [0.000004, 0.000004, 0.0009]

[[cars]]
optimise_dt = 0.01
horizon_dt = 0.04
N = 45
model = "no_slip_point"
initial_params = [0.07, 3.9, 10.0, 19.6, 14.2, 1.8, 0.0045]
controller = "mpc_raceline"
estimator = "joint_ukf"
# State evolution variance
Q_state = [0.00002, 0.00002, 0.0001, 0.0002, 0.0001]
# Initial parameter variance
Q_initial_params = [0.005, 0.005, 0.05, 0.005, 0.004, 0.003, 0.0]
# Q_params = Q_initial_params * Q_params_multiplier
Q_params_multiplier = 0.0000000001
u_min = [0.0, -0.8]
u_max = [0.3, 0.8]
