t = 200
# Run the simulator in real time instead of as fast as possible
real_time = true
model = "kinematic_bicycle"
# C1: Steering slip - negative for oversteer, positive for understeer
# C2: Steering angle coupling - radians turned / meter travelled
# C3: ...
# Cm1: Duty cycle to acceleration a = Cm1 * throttle
# Cm2 = Cm1 / v_motor_max (i.e. max speed with no air resistance)
# Cr1: Rolling resistance
# Cr2: Reduced air resistance coefficient (0.5 * rho * A * C_d)
params = [0.5, 15.0, 0.6, 19.6, 14.2, 1.8, 0.0045]
R = [0.000004, 0.000004, 0.0009]
Q_state = [0.000001, 0.000001, 0.000001, 0.000001, 0.000001]
